# Server properties
server:
  port: 8081
  servlet:
    context-path: /api/v1
  error:
    include-stacktrace: never

# Spring Boot properties
spring:
  application:
    name: auth-service
  config:
    import: optional:file:.env[.properties]
  mvc:
    log-resolved-exception: true
  datasource:
    url: 'jdbc:postgresql://localhost:5431/auth'
    username: 'postgres'
    password: 'postgres'
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: never
