version: "3.7"
services:
  auth-database:
    image: postgres:14.4
    container_name: auth-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - 5431:5432
    networks:
      - auth-network
      - kafka-network
    volumes:
      - auth-database:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  account-database:
    image: postgres:14.4
    container_name: account-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account
    ports:
      - 5432:5432
    networks:
      - account-network
      - kafka-network
    volumes:
      - account-database:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: 'bitnami/zookeeper:3.8'
    container_name: zookeeper
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    networks:
      - kafka-network
    volumes:
      - 'zookeeper:/bitnami/zookeeper'

  kafka:
    image: 'bitnami/kafka:3.4'
    container_name: kafka
    restart: unless-stopped
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ENABLE_KRAFT=no
    ports:
      - '9092:9092'
      - '9094:9094'
    networks:
      - kafka-network
    volumes:
      - 'kafka:/bitnami/kafka'
    depends_on:
      - zookeeper

volumes:
  auth-database:
  account-database:
  zookeeper:
  kafka:

networks:
  auth-network:
    driver: bridge
  account-network:
    driver: bridge
  kafka-network:
    driver: bridge